[program:laravel-worker]

process_name=%(program_name)s_%(process_num)02d

directory=/home/sysadmin/bagi-hoki

command=php artisan queue:work --queue=tickets,imports,draws,reports,default --daemon --sleep=3 --tries=3 --max-time=3600

autostart=true

autorestart=true

stopasgroup=true

killasgroup=true

user=sysadmin ; Or your deployment user

numprocs=8 ; Number of worker processes to run

redirect_stderr=true

stdout_logfile=/home/sysadmin/bagi-hoki/storage/logs/workers.log

stopwaitsecs=3600